use_frameworks!
platform :ios, '10.0'

source 'git@git.silvrr.com:Asetku/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'ZJRemoteNotification_Example' do
  
  pod 'ZJRemoteNotification', :path => '../'

end
