use_frameworks!

platform :ios, '10.0'

target 'ZJRemoteNotification_Example' do
  pod 'ZJRemoteNotification', :path => '../'

  target 'ZJRemoteNotification_Tests' do
    inherit! :search_paths

    
  end
end
